### ISSUE TITLE
求指教

### ISSUE THREAD

**Issue by 79660095** [FamliarMan/AutoLocateHorizontalView#1]
大神    你写的这个很类似我要的效果  但是可以点击某个按钮 往左边移动一步  或者往右移动一步吗  求解谢谢你了。

**Comment by FamliarMan** [comment]
这个改起来应该不难，你可以看下我的初始化时是如何选中某个位置的，用类似的方法可以实现，我最近没时间，有时间可以加上

**Comment by FamliarMan** [comment]
你要的功能我加上了……
