### ISSUE TITLE
为什么我集成之后  一滑动就崩溃，报错信息如下：

### ISSUE THREAD

**Issue by LiHexiang** [FamliarMan/AutoLocateHorizontalView#2]
java.lang.ClassNotFoundException:android.support.v4.animation.AnimatorCompatHelper

**Comment by FamliarMan** [comment]
首先确认下不集成这个控价还报不报错，其次分析下support包的依赖，将这个module的support包排除，使用自己本身的support包，然后看看能不能解决这个问题。

**Comment by LiHexiang** [comment]
嗯，确实是support包的版本冲突，但是我是直接把你的那个类拷贝到项目中的，没有依赖那个module，所以我也不知道怎么解决这种情况的版本冲突，不过我找到了报错的位置，是在DefaultAnimator中，所以我暂时是设置recyclerView.getItemAnimator().setSupportsChangeAnimations(false),禁用了item的动画暂时解决了这个问题，不知道大神有啥好的办法，感谢及时回答

**Comment by FamliarMan** [comment]
出现这种情况的话，你要不检查下RecyclerView和support包的版本号是否统一？不统一的话试着统一下看看，不然我也没办法了。
